/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTrashIndexRouteImport } from './routes/_layout/trash/index'
import { Route as LayoutPagePageIdIndexRouteImport } from './routes/_layout/page/$pageId/index'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutTrashIndexRoute = LayoutTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagePageIdIndexRoute = LayoutPagePageIdIndexRouteImport.update({
  id: '/page/$pageId/',
  path: '/page/$pageId/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/trash/': typeof LayoutTrashIndexRoute
  '/page/$pageId/': typeof LayoutPagePageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/trash': typeof LayoutTrashIndexRoute
  '/page/$pageId': typeof LayoutPagePageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/trash/': typeof LayoutTrashIndexRoute
  '/_layout/page/$pageId/': typeof LayoutPagePageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/trash/' | '/page/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/trash' | '/page/$pageId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/_layout/trash/'
    | '/_layout/page/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/trash/': {
      id: '/_layout/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof LayoutTrashIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/page/$pageId/': {
      id: '/_layout/page/$pageId/'
      path: '/page/$pageId'
      fullPath: '/page/$pageId/'
      preLoaderRoute: typeof LayoutPagePageIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTrashIndexRoute: typeof LayoutTrashIndexRoute
  LayoutPagePageIdIndexRoute: typeof LayoutPagePageIdIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTrashIndexRoute: LayoutTrashIndexRoute,
  LayoutPagePageIdIndexRoute: LayoutPagePageIdIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
